all:
ifeq ($(OS),Windows_NT)
	# assume windows
	javac -Xlint -cp ".;lucene-6.6.0/*" -g *.java
else
	# assume Linux
	javac -Xlint -cp "/Users/yidingou/Desktop/CMU/11-642/lucene-6.6.0/*" -g *.java
endif
